<script>
export default {
    name: 'DetailsBody',
}
</script>

<template>
    <div class="container">
        <div class="posts-table">
            <div class="navigate">
                <span><a href="./../../../index.html">My Forum - Forums</a> >> <a href="./../../../posts.html">Random
                        Forum</a></span> >> <span><a href="../../../details.html">Random Post</a></span>
            </div>
        </div>
    </div>

    <div class="topic-container">
        <div class="head">
            <div class="author">Author</div>
            <div class="content">Topic: post's title (Read 1258 Times)</div>
        </div>

        <div class="body">
            <div class="authors">
                <div class="username"><a href="#">Username</a></div>
                <div>Role</div>
                <img src="https://cdn.pixabay.com/photo/2017/08/09/18/51/dragon-2615470_1280.png" alt="dragon">
                <div>Posts: <u>45</u></div>
                <div>Points: <u>5423</u></div>
            </div>

            <div class="content">
                Just a random content <br>generated by simone's the great <br><br>
                with his hugely overwhelming intelligence.
                <br><br>
                <hr>
                Regards Username
            </div>

        </div>
    </div>

    <div class="topic-container">
        <div class="head">
            <div class="author">Author</div>
            <div class="content">Topic: post's title (Read 1258 Times)</div>
        </div>

        <div class="body">
            <div class="authors">
                <div class="username"><a href="#">Username</a></div>
                <div>Role</div>
                <img src="https://cdn.pixabay.com/photo/2017/08/09/18/51/dragon-2615470_1280.png" alt="dragon">
                <div>Posts: <u>45</u></div>
                <div>Points: <u>5423</u></div>
            </div>

            <div class="content">
                Just a random content <br>generated by simone's the great <br><br>
                with his hugely overwhelming intelligence.
                <br><br>
                <hr>
                Regards Username
            </div>

        </div>
    </div>

    <div class="topic-container">
        <div class="head">
            <div class="author">Author</div>
            <div class="content">Topic: post's title (Read 1258 Times)</div>
        </div>

        <div class="body">
            <div class="authors">
                <div class="username"><a href="#">Username</a></div>
                <div>Role</div>
                <img src="https://cdn.pixabay.com/photo/2017/08/09/18/51/dragon-2615470_1280.png" alt="dragon">
                <div>Posts: <u>45</u></div>
                <div>Points: <u>5423</u></div>
            </div>

            <div class="content">
                Just a random content <br>generated by simone's the great <br><br>
                with his hugely overwhelming intelligence.
                <br><br>
                <hr>
                Regards Username
            </div>

        </div>
    </div>

    <div class="topic-container">
        <div class="head">
            <div class="author">Author</div>
            <div class="content">Topic: post's title (Read 1258 Times)</div>
        </div>

        <div class="body">
            <div class="authors">
                <div class="username"><a href="#">Username</a></div>
                <div>Role</div>
                <img src="https://cdn.pixabay.com/photo/2017/08/09/18/51/dragon-2615470_1280.png" alt="dragon">
                <div>Posts: <u>45</u></div>
                <div>Points: <u>5423</u></div>
            </div>

            <div class="content">
                Just a random content <br>generated by simone's the great <br><br>
                with his hugely overwhelming intelligence.
                <br><br>
                <hr>
                Regards Username
            </div>

        </div>
    </div>

    <div class="topic-container">
        <div class="head">
            <div class="author">Author</div>
            <div class="content">Topic: post's title (Read 1258 Times)</div>
        </div>

        <div class="body">
            <div class="authors">
                <div class="username"><a href="#">Username</a></div>
                <div>Role</div>
                <img src="https://cdn.pixabay.com/photo/2017/08/09/18/51/dragon-2615470_1280.png" alt="dragon">
                <div>Posts: <u>45</u></div>
                <div>Points: <u>5423</u></div>
            </div>

            <div class="content">
                Just a random content <br>generated by simone's the great <br><br>
                with his hugely overwhelming intelligence.
                <br><br>
                <hr>
                Regards Username
            </div>

        </div>
    </div>
</template>

<style scoped>
/* navigation */

.container {
    & .navigate {
        margin-block: 20px;
        font-weight: lighter;
        font-size: 24px;

        & a {
            color: #fff;
        }

        & a:hover {
            color: #ff0042;
            font-weight: bolder;
        }
    }
}

.topic-container {
    max-width: 95%;
    margin: auto auto .5rem auto;

    & .head {
        display: flex;
        background-color: #2c2c2c;
        padding: 5px;
        font-weight: bold;
        font-size: 15px;

        & .author {
            flex: 20%;
        }

        & .content {
            flex: 80%;
        }
    }

    & .body {
        display: flex;
        background-color: #131415;
        padding: 10px;
        margin-top: 5px;
        font-weight: bold;
        font-size: 10px;

        & .authors {
            flex: 20%;

            & img {
                max-width: 100px;
                max-height: 570px;
                background-color: white;
            }
        }

        & .content {
            flex: 80%;
            font-size: 15px;
            padding: 15px 15px 15px 0;

            >hr {
                margin-bottom: .5rem;
            }
        }
    }

}
</style>